[versions]
coroutines = "1.10.2"
sqldelight = "2.2.1"

[libraries]
cloud-spanner-r2dbc = { module = "com.google.cloud:cloud-spanner-r2dbc", version = "1.4.1" }

sqldelight-r2dbc-driver = { module = "app.cash.sqldelight:r2dbc-driver", version.ref = "sqldelight" }
sqldelight-async-extensions = { module = "app.cash.sqldelight:async-extensions", version.ref = "sqldelight" }
sqldelight-postgresql-dialect = { module = "app.cash.sqldelight:postgresql-dialect", version.ref = "sqldelight" }

coroutines-reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor", version.ref = "coroutines" }

logback = { module = "ch.qos.logback:logback-classic", version = "1.5.22" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.2.21" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
licensee = { id = "app.cash.licensee", version = "1.14.1" }
